In [29]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
print("h11 y h12 " + str(hidden_layer_input))
hidden_layer_output = sigmoid(hidden_layer_input)
print("S(h11) y S(h12) " + str(hidden_layer_output))
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
output

h11 y h12 [ 0.24 -0.46]
S(h11) y S(h12) [0.55971365 0.38698582]


0.48497343084992534

In [20]:
## Backwards pass
## TODO: Calculate output error
error = target - output
error

0.11502656915007464

In [32]:
# TODO: Calculate error term for output layer lower case delta°
output_error_term = error * output * (1 - output)
output_error_term

0.028730669543515018

In [34]:
# TODO: Calculate error term for hidden layer lower case delta h
hidden_error_term = weights_hidden_output  * output_error_term * hidden_layer_output *(1-hidden_layer_output)
hidden_error_term

array([ 0.00070802, -0.00204471])

In [35]:
# TODO: Calculate change in weights for hidden layer to output layer DELTA W
delta_w_h_o = learnrate * output_error_term * hidden_layer_output
delta_w_h_o

array([0.00804047, 0.00555918])

In [36]:
# TODO: Calculate change in weights for input layer to hidden layer DELTA wi
delta_w_i_h = (learnrate * hidden_error_term)*x[:,None]
delta_w_i_h

array([[ 1.77005547e-04, -5.11178506e-04],
       [ 3.54011093e-05, -1.02235701e-04],
       [-7.08022187e-05,  2.04471402e-04]])

In [37]:
print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]
