In [72]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


In [73]:
# TODO: Make a forward pass through the network

#input hidden layer

hidden_layer_in = np.dot(X,weights_input_to_hidden)


In [74]:
# Pass the input of the layer to the activation fucntion
hidden_layer_out = sigmoid(hidden_layer_in)
hidden_layer_out

array([0.41492192, 0.42604313, 0.5002434 ])

In [76]:
# Create the input for the next layer

output_layer_in= np.dot(hidden_layer_out,weights_hidden_to_output)
output_layer_in

array([-0.00739221, -0.05842573])

In [77]:
# pass the input for the activation function

output_layer_out = sigmoid(output_layer_in)
output_layer_out

array([0.49815196, 0.48539772])

In [78]:
print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out,weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]
